server:
  port: 8081

spring:
  application:
    name: consumer
  cloud:
    servicecomb:
      discovery:
        address: http://127.0.0.1:30100
servicecomb:
  match:
    demo-rateLimiting: |
      matches:
        - apiPath:
            exact: "/hello"
    demo-retry: |
      matches:
        - apiPath:
            exact: "/retry"
    demo-circuitBreaker: |
      matches:
        - apiPath:
            exact: "/circuitBreaker"
  rateLimiting:
    xxxxx: |
      match: demo-rateLimiting
      rate: 1
  retry:
    xxx: |
      match: demo-retry
      maxAttempts: 3
  circuitBreaker:
    xxx: |
      match: demo-circuitBreaker
      minimumNumberOfCalls: 2
      slidingWindowSize: 2