language: java

jdk:
  - openjdk8

jobs:
  include:
    - stage: findbugs
      script:
        - mvn clean package findbugs:findbugs -Dmaven.test.skip=true  -Dmaven.javadoc.skip=true --settings .travis.settings.xml
    - stage: install
      script:
        - mvn install -Dmaven.javadoc.skip=true --settings .travis.settings.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)