server:
  port: 8080

spring:
  application:
    name: price
  cloud:
    servicecomb:
      discovery:
        enabled: true
        address: https://cse.cn-east-2.myhuaweicloud.com
        serviceName: price
        version: 0.0.1
        healthCheckInterval: 30
      credentials:
        enable: true
        accessKey: H4ETIVFGP7W7AMMLU8KB
        secretKey: Gh7GOuSM7Va03JwKovqFhxQJPbhPJ6lOwWnaceBo
        akskCustomCipher: default
        project: cn-east-2
cse:
  config:
    client:
      serverUri: https://cse.cn-east-2.myhuaweicloud.com
      refreshMode: 1
      refresh_interval: 5000
