server:
  port: 8081

spring:
  application:
    name: backend-service
  cloud:
    servicecomb:
      discovery:
        enabled: true
        address: http://127.0.0.1:30100
        version: 0.0.1
        healthCheckInterval: 30