server:
  port: 8080

spring:
  application:
    name: spring-cloud-servicecomb
  cloud:
    servicecomb:
      discovery:
        enabled: true
        address: http://127.0.0.1:30300
        serviceName: price
        version: 0.0.1