server:
  port: 8080

spring:
  application:
    name: reserve
  cloud:
    servicecomb:
      discovery:
        enabled: true
        address: https://cse.cn-north-4.myhuaweicloud.com
        version: 0.0.1
        healthCheckInterval: 30
      credentials:
        enabled: true
        accessKey: your ak
        secretKey: your sk
        akskCustomCipher: default
        project: cn-north-4

dtm:
  appName: reserve
  rpc:
    sslEnabled: true
  proxy:
    endpoint: https://192.168.0.207:30125
